version: '3'

services:
    app:
        build:
            context: .
        environment:
            - NODE_ENV=development
            - PORT=3000
        command: npm start
        ports:
            - 3000:3000
        networks: 
            - dev-network
        links:
            - redis
            - postgres
        depends_on: 
            - redis
            - postgres
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        hostname: redis
        volumes:
            - ./redis/data:/data
        networks: 
            - dev-network
    postgres:
        image: postgres:latest
        ports:  
            - 5432:5432
        hostname: postgres
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks: 
            - dev-network
volumes:
    esdata1:
        driver: local
networks: 
    dev-network:
        driver: bridge
